import UserState from "@/context/userState";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <script
                    async
                    src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5294151828912060"
                    crossorigin="anonymous"
                ></script>
            </head>
            <body className={inter.className}>
                <UserState>{children}</UserState>
            </body>
        </html>
    );
}
